const data = [
  {
    letter: "א",
    image: require("./images/alef.png"),
    imageCursive: require("./images/alefCursive.png"),
    name: "Aleph",
    sound: "a",
    id: 1,
  },
  {
    letter: "ב",
    image: require("./images/bet.png"),
    imageCursive: require("./images/betCursive.png"),
    name: "Bet",
    sound: "b",
    id: 2,
  },
  {
    letter: "ג",
    image: require("./images/gimel.png"),
    imageCursive: require("./images/gimelCursive.png"),
    name: "Gimel",
    sound: "g",
    id: 3,
  },
  {
    letter: "ד",
    image: require("./images/dalet.png"),
    imageCursive: require("./images/daletCursive.png"),
    name: "Dalet",
    sound: "d",
    id: 4,
  },
  {
    letter: "ה",
    image: require("./images/he.png"),
    imageCursive: require("./images/heCursive.png"),
    name: "He",
    sound: "h",
    id: 5,
  },
  {
    letter: "ו",
    image: require("./images/vav.png"),
    imageCursive: require("./images/vavCursive.png"),
    name: "Vav",
    sound: "v",
    id: 6,
  },
  {
    letter: "ז",
    image: require("./images/zayin.png"),
    imageCursive: require("./images/zayinCursive.png"),
    name: "Zayin",
    sound: "z",
    id: 7,
  },
  {
    letter: "ח",
    image: require("./images/het.png"),
    imageCursive: require("./images/hetCursive.png"),
    name: "Het",
    sound: "h",
    id: 8,
  },
  {
    letter: "ט",
    image: require("./images/tet.png"),
    imageCursive: require("./images/tetCursive.png"),
    name: "Tet",
    sound: "t",
    id: 9,
  },
  {
    letter: "י",
    image: require("./images/yod.png"),
    imageCursive: require("./images/yodCursive.png"),
    name: "Yod",
    sound: "y",
    id: 10,
  },
  {
    letter: "כ",
    image: require("./images/caf.png"),
    imageCursive: require("./images/cafCursive.png"),
    name: "Kaf",
    sound: "k",
    id: 11,
  },
  {
    letter: "ך",
    image: require("./images/kafSofit.png"),
    imageCursive: require("./images/cafCursive.png"),
    name: "Kaf Sofit",
    sound: "k",
    id: 12,
  },
  {
    letter: "ל",
    image: require("./images/lamed.png"),
    imageCursive: require("./images/lamedCursive.png"),
    name: "Lamed",
    sound: "l",
    id: 13,
  },
  {
    letter: "מ",
    image: require("./images/mem.png"),
    imageCursive: require("./images/memCursive.png"),
    name: "Mem",
    sound: "m",
    id: 14,
  },
  {
    letter: "ם",
    image: require("./images/memSofit.png"),
    imageCursive: require("./images/memSofitCursive.png"),
    name: "Mem Sofit",
    sound: "m",
    id: 15,
  },
  {
    letter: "נ",
    image: require("./images/nun.png"),
    imageCursive: require("./images/nunCursive.png"),
    name: "Nun",
    sound: "n",
    id: 16,
  },
  {
    letter: "ן",
    image: require("./images/nunSofit.png"),
    imageCursive: require("./images/nunSofitCursive.png"),
    name: "Nun Sofit",
    sound: "n",
    id: 17,
  },
  {
    letter: "ס",
    image: require("./images/samekh.png"),
    imageCursive: require("./images/samekhCursive.png"),
    name: "Samekh",
    sound: "s",
    id: 18,
  },
  {
    letter: "ע",
    image: require("./images/ayin.png"),
    imageCursive: require("./images/ayinCursive.png"),
    name: "Ayin",
    sound: "a",
    id: 19,
  },
  {
    letter: "פ",
    image: require("./images/pe.png"),
    imageCursive: require("./images/peCursive.png"),
    name: "Pe",
    sound: "p",
    id: 20,
  },
  {
    letter: "ף",
    image: require("./images/peSofit.png"),
    imageCursive: require("./images/peSofitCursive.png"),
    name: "Pe Sofit",
    sound: "p",
    id: 21,
  },
  {
    letter: "צ",
    image: require("./images/tsadi.png"),
    imageCursive: require("./images/tsadiCursive.png"),
    name: "Tsadi",
    sound: "ts",
    id: 22,
  },
  {
    letter: "ץ",
    image: require("./images/tsadiSofit.png"),
    imageCursive: require("./images/tsadiSofitCursive.png"),
    name: "Tsadi Sofit",
    sound: "ts",
    id: 23,
  },
  {
    letter: "ק",
    image: require("./images/qof.png"),
    imageCursive: require("./images/qofCursive.png"),
    name: "Qof",
    sound: "q",
    id: 24,
  },
  {
    letter: "ר",
    image: require("./images/resh.png"),
    imageCursive: require("./images/reshCursive.png"),
    name: "Resh",
    sound: "r",
    id: 25,
  },
  {
    letter: "ש",
    image: require("./images/shin.png"),
    imageCursive: require("./images/shinCursive.png"),
    name: "Shin",
    sound: "sh",
    id: 26,
  },
  {
    letter: "ת",
    image: require("./images/tav.png"),
    imageCursive: require("./images/tavCursive.png"),
    name: "Tav",
    sound: "t",
    id: 27,
  },
];

export default data;
